#
#   Copyright 2012 Wade Alcorn wade@bindshell.net
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
beef:
    module:
        iframe_above:
            enable: true
            category: "Persistence"
            name: "Create Foreground iFrame"
            description: "Rewrites all links on the webpage to spawn a 100% by 100% iFrame with a source relative to the selected link."
            authors: ["passbe"]
            target:
                user_notify: ["ALL"]
