#
#   Copyright 2012 Wade Alcorn wade@bindshell.net
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
beef:
    module:
        clipboard_theft:
            enable: true
            category: "Host"
            name: "Get Clipboard"
            description: "Retrieves the clipboard contents. This module will work automatically with Internet Explorer 6.x however Internet Explorer 7.x will prompt the user and ask for permission to access the clipboard."
            authors: ["bcoles"]
            target:
                working: 
                    IE:
                        min_ver: 6
                        max_ver: 6
                user_notify:
                    IE:
                        min_ver: 7
                        max_ver: 7
                not_working: ["All"]

