#
#   Copyright 2012 Wade Alcorn wade@bindshell.net
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
beef:
    module:
        popunder_window:
            enable: true
            category: "Persistence"
            name: "Create Pop Under"
            description: "This module creates a new discrete pop under window with the BeEF hook included.<br><br>Another browser node will be added to the hooked browser tree."
            authors: ["ethicalhack3r"]
            target:
                user_notify: ["ALL"]
